/**
 * Platform Adapter Interface
 * 
 * @see specs/001-ai-subtitle-translator/contracts/platform-adapter.md
 */

import type { Platform, SubtitleFormat, Cue } from '../../shared/types/subtitle';

/**
 * URL pattern for matching platform pages
 */
export interface URLPattern {
  /** Regex pattern to match URLs */
  pattern: RegExp;
  /** Whether this is the main video page or an embed */
  type: 'main' | 'embed';
}

/**
 * Represents an available subtitle track
 */
export interface SubtitleTrack {
  /** Track identifier (platform-specific) */
  id: string;
  
  /** Language code (BCP 47) */
  language: string;
  
  /** Display name */
  label: string;
  
  /** URL to fetch the subtitle */
  url: string;
  
  /** Subtitle format */
  format: SubtitleFormat;
  
  /** Whether this is auto-generated (ASR) */
  isAutoGenerated: boolean;
  
  /** Whether this is the default track */
  isDefault: boolean;
}

/**
 * Raw subtitle content from platform
 */
export interface RawSubtitle {
  /** Raw content as string */
  content: string;
  
  /** Content format */
  format: SubtitleFormat;
  
  /** Additional metadata from the platform */
  metadata?: Record<string, unknown>;
}

/**
 * Options for rendering subtitles
 */
export interface RenderOptions {
  /** Font size in pixels */
  fontSize: number;

  /** Font color in hex format (e.g., '#FFFFFF') */
  fontColor: string;

  /** Position on screen */
  position: 'top' | 'bottom';

  /** Show bilingual subtitles */
  bilingual: boolean;

  /** If bilingual, which is on top */
  bilingualOrder: 'original-first' | 'translation-first';

  /** Background style */
  background: 'none' | 'shadow' | 'box';

  /** Font family */
  fontFamily: string;

  /**
   * Whether to hide native platform subtitles when showing translated overlay.
   * - true: Hide native subtitles (show only our overlay with original + translation)
   * - false: Keep native subtitles visible (show translation overlay alongside native)
   *
   * When false, this allows users to see progressive word-by-word native subtitles
   * while also seeing the complete translated sentence overlay. This is especially
   * useful for ASR (auto-generated) subtitles where the native display shows
   * progressive word-by-word timing.
   *
   * Default: true (hide native subtitles)
   */
  hideNativeSubtitles?: boolean;
}

/**
 * Video events for time synchronization
 */
export type VideoEvent = 
  | { type: 'play' }
  | { type: 'pause' }
  | { type: 'seeked'; currentTime: number }
  | { type: 'timeupdate'; currentTime: number }
  | { type: 'ended' }
  | { type: 'ratechange'; playbackRate: number };

/**
 * Callback for video events
 */
export type VideoEventCallback = (event: VideoEvent) => void;

/**
 * Platform Adapter Interface
 * 
 * Each streaming platform (YouTube, Netflix, Disney+, Prime Video) must implement
 * this interface to enable subtitle interception and rendering.
 */
export interface PlatformAdapter {
  /** Platform identifier */
  readonly platform: Platform;
  
  /** URL patterns this adapter handles */
  readonly urlPatterns: URLPattern[];
  
  /**
   * Check if this adapter can handle the current page
   */
  canHandle(url: string): boolean;
  
  /**
   * Initialize the adapter on the page
   * Called when the content script loads on a matching page
   */
  initialize(): Promise<void>;
  
  /**
   * Get the current video ID from the page
   */
  getVideoId(): string | null;
  
  /**
   * Get available subtitle tracks for the current video
   */
  getSubtitleTracks(): Promise<SubtitleTrack[]>;
  
  /**
   * Fetch the subtitle content for a specific track
   */
  fetchSubtitle(track: SubtitleTrack): Promise<RawSubtitle>;
  
  /**
   * Inject translated subtitles into the player
   */
  injectSubtitles(cues: Cue[], options: RenderOptions): void;
  
  /**
   * Remove injected subtitles
   */
  removeSubtitles(): void;
  
  /**
   * Get the video element reference
   */
  getVideoElement(): HTMLVideoElement | null;
  
  /**
   * Subscribe to video events (play, pause, seek, etc.)
   */
  onVideoEvent(callback: VideoEventCallback): () => void;
  
  /**
   * Clean up when navigating away
   */
  destroy(): void;
}

/**
 * Adapter error codes
 */
export type AdapterErrorCode =
  | 'INITIALIZATION_FAILED'
  | 'VIDEO_NOT_FOUND'
  | 'SUBTITLE_FETCH_FAILED'
  | 'SUBTITLE_PARSE_FAILED'
  | 'INJECTION_FAILED'
  | 'PLATFORM_UPDATED'
  | 'UNSUPPORTED_CONTENT';

/**
 * Adapter error class
 */
export class AdapterError extends Error {
  constructor(
    public code: AdapterErrorCode,
    message: string,
    public platform: Platform
  ) {
    super(message);
    this.name = 'AdapterError';
  }
}

/**
 * Default render options
 */
export const DEFAULT_RENDER_OPTIONS: RenderOptions = {
  fontSize: 28,
  fontColor: '#FFFFFF',
  position: 'bottom',
  bilingual: true,
  bilingualOrder: 'original-first',
  background: 'box',
  fontFamily: 'system-ui, -apple-system, sans-serif',
  hideNativeSubtitles: true
};
